[package]
name = "systemvisor"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "systemvisor"
path = "src/main.rs"

[dependencies]
ratatui = { version = "0.26", features = ["crossterm"] }
crossterm = { version = "0.27", features = [] }
sysinfo = "0.30"
crossbeam-channel = "0.5"
panic-hook = "0.1"
